version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - ./envs/db.env

  cache:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass redispasswd
    volumes:
      - ./cache:/data

  django:
    build: ./django/
    command: bash -c "
      pipenv run python manage.py makemigrations
      && pipenv run python manage.py migrate
      && pipenv run python manage.py collectstatic --noinput
      && pipenv run uwsgi  --ini django.uwsgi.ini"
    volumes:
      - ./django/:/code/
      - uwsgi_data:/tmp/uwsgi/
      - web_static:/code/static/
      - web_static:/var/www/web/assets/
    env_file:
      - ./envs/django.env
    depends_on:
      - db
      - cache

  nginx:
    build:
      context: ./nginx/
      args:
        CONF_FILE: ${NGINX_CONF}
    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - web_static:/var/www/web/assets/:ro
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    depends_on:
      - django

volumes:
  uwsgi_data:
  web_static:
